In [29]:
import pandas as pd
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

In [46]:
def LoadData(input_file) :
    data = pd.read_csv(input_file, encoding="UTF-8")
    #reader = tf.TextLineReader(skip_header_lines=1)
    #_, csv_row = reader.read(input_file)
    
    data.head()
    
    features = data.copy()
    labels = features.pop('Price')
    features = np.array(features).astype(float)

    return features, labels

In [47]:
def Normalize(data):
    normalize = preprocessing.Normalization()
    normalize.adapt(data)
    return normalize

In [48]:
def train(features, labels) :
    print(features)
    
    model = tf.keras.Sequential([
        #Normalize(features),
        layers.Dense(16),
        layers.Dense(1)
    ])
    
    model.compile(loss = tf.losses.MeanSquaredError(), 
                  optimizer = tf.optimizers.Adam())
    model.fit(features, labels, epochs=1000)

In [ ]:
f, l = LoadData('data/ev-train-data.csv')
train(f, l)

[[1.000e+00 1.000e+00 2.010e+03 ... 1.000e+00 1.100e+01 1.000e+00]
 [2.000e+00 1.000e+00 2.015e+03 ... 2.000e+00 2.000e+00 2.000e+00]
 [3.000e+00 1.000e+00 2.011e+03 ... 1.000e+00 1.100e+01 1.000e+00]
 ...
 [2.000e+00 1.000e+00 2.012e+03 ... 1.000e+00 1.100e+01 1.000e+00]
 [3.000e+00 1.000e+00 2.013e+03 ... 2.000e+00 2.000e+00 2.000e+00]
 [1.000e+00 1.000e+00 2.011e+03 ... 1.000e+00 1.100e+01 1.000e+00]]
Epoch 1/1000
189/189 [==============================] - 1s 2ms/step - loss: nan
Epoch 2/1000
189/189 [==============================] - 0s 2ms/step - loss: nan
Epoch 3/1000
189/189 [==============================] - ETA: 0s - loss: n - 0s 2ms/step - loss: nan
Epoch 4/1000
189/189 [==============================] - 0s 1ms/step - loss: nan
Epoch 5/1000
189/189 [==============================] - 0s 1ms/step - loss: nan
Epoch 6/1000
189/189 [==============================] - 0s 1ms/step - loss: nan
Epoch 7/1000
189/189 [==============================] - 0s 1ms/step - loss: nan
Epoch 8/1000

189/189 [==============================] - 1s 3ms/step - loss: nan
Epoch 97/1000
189/189 [==============================] - 0s 2ms/step - loss: nan
Epoch 98/1000
189/189 [==============================] - 0s 1ms/step - loss: nan
Epoch 99/1000
189/189 [==============================] - 0s 1ms/step - loss: nan
Epoch 100/1000
  1/189 [..............................] - ETA: 0s - loss: nan

## 다중선형회귀 sample

In [24]:
import tensorflow as tf

F_CNT = 16

x1 = [73, 93, 89, 96, 73]
x2 = [80, 88, 91, 98, 66]
x3 = [75, 93, 90, 100, 70]
y = [152, 185, 180, 196, 142]

w1 = tf.Variable(tf.random.normal([1]))
w2 = tf.Variable(tf.random.normal([1]))
w3 = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))

learning_rate = 0.000001

for i in range(1000+1) : 
    with tf.GradientTape() as tape:
        h = w1*x1 + w2*x2 + w3*x3 + b
        cost = tf.reduce_mean(tf.square(h-y))
        
        w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
        
        w1.assign_sub(learning_rate * w1_grad)
        w2.assign_sub(learning_rate * w2_grad)
        w3.assign_sub(learning_rate * w3_grad)
        b.assign_sub(learning_rate * b_grad)
        
        if i%50 == 0:
            print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 |   23879.3008
   50 |     294.6528
  100 |      32.8810
  150 |      29.9010
  200 |      29.7929
  250 |      29.7167
  300 |      29.6412
  350 |      29.5659
  400 |      29.4909
  450 |      29.4158
  500 |      29.3411
  550 |      29.2667
  600 |      29.1923
  650 |      29.1181
  700 |      29.0443
  750 |      28.9705
  800 |      28.8970
  850 |      28.8237
  900 |      28.7506
  950 |      28.6775
 1000 |      28.6049
